"""TM: add winner/completed; p1/p2 nullable + SET NULL

Revision ID: 1c9346b310ec
Revises: 15a18e45227a
Create Date: 2025-10-02 12:44:14.677603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c9346b310ec'
down_revision: Union[str, Sequence[str], None] = '15a18e45227a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('participant1_id', sa.Integer(), nullable=True),
    sa.Column('participant2_id', sa.Integer(), nullable=True),
    sa.Column('challonge_id', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('winner_participant_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['participant1_id'], ['tournament_participants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['participant2_id'], ['tournament_participants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_participant_id'], ['tournament_participants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'challonge_id', name='uq_tm_t_chid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournament_matches')
    # ### end Alembic commands ###
