"""add cws win checkin column in User model

Revision ID: 1efcbc8a3af1
Revises: 757c9e70b2f2
Create Date: 2025-11-02 08:56:40.879896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1efcbc8a3af1'
down_revision: Union[str, Sequence[str], None] = '757c9e70b2f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('crew_wars_wins_checkin', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'crew_wars_wins_checkin')
    # ### end Alembic commands ###
