"""Add Column for tier in Pokemon

Revision ID: 357d7312af9a
Revises: 44c5bd1d311a
Create Date: 2025-08-03 11:33:00.841844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '357d7312af9a'
down_revision: Union[str, Sequence[str], None] = '44c5bd1d311a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('tier', sa.String(length=16), nullable=True))
    op.add_column('pokemon', sa.Column('always_stored', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pokemon', 'always_stored')
    op.drop_column('pokemon', 'tier')
    # ### end Alembic commands ###
