"""Add column in Tournament participants for received rewards

Revision ID: 36a1a16a2b77
Revises: d8149eb81d65
Create Date: 2025-10-23 22:36:00.781387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36a1a16a2b77'
down_revision: Union[str, Sequence[str], None] = 'd8149eb81d65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_participants', sa.Column('reward_received', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament_participants', 'reward_received')
    # ### end Alembic commands ###
