"""Add always stored column to pokemon table

Revision ID: 44c5bd1d311a
Revises: b030be4c7628
Create Date: 2025-08-03 00:24:06.650614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44c5bd1d311a'
down_revision: Union[str, Sequence[str], None] = 'b030be4c7628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
