"""add battle url column in tournament matches

Revision ID: 45c17e439e69
Revises: 2330fd72e4e0
Create Date: 2025-10-07 22:05:35.638952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45c17e439e69'
down_revision: Union[str, Sequence[str], None] = '2330fd72e4e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_participants', sa.Column('battle_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament_participants', 'battle_url')
    # ### end Alembic commands ###
