"""add tournaments + participants

Revision ID: 4d962611033d
Revises: b99403bebda0
Create Date: 2025-09-30 21:35:55.575387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d962611033d'
down_revision: Union[str, Sequence[str], None] = 'b99403bebda0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'pvp_experience',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Text(),
               existing_nullable=False,
               existing_server_default=sa.text("'novice'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'pvp_experience',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False,
               existing_server_default=sa.text("'novice'::character varying"))
    # ### end Alembic commands ###
