"""add datetime for received rewards model

Revision ID: 50f812c6cb1f
Revises: ed7b03e4cb2a
Create Date: 2025-10-31 09:18:08.881453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50f812c6cb1f'
down_revision: Union[str, Sequence[str], None] = 'ed7b03e4cb2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_participants', sa.Column('reward_received_on', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament_participants', 'reward_received_on')
    # ### end Alembic commands ###
