"""add current_tournament column to Tournaments table

Revision ID: 577e9df3ca28
Revises: b13c89ae8569
Create Date: 2025-09-30 23:33:16.753420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '577e9df3ca28'
down_revision: Union[str, Sequence[str], None] = 'b13c89ae8569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
