"""change country_timezone to timezone and add timezone_name column

Revision ID: 73c957aba8da
Revises: 9bd9dcbf13e1
Create Date: 2025-10-07 02:00:33.102673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73c957aba8da'
down_revision: Union[str, Sequence[str], None] = '9bd9dcbf13e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('country', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('timezone_name', sa.Text(), nullable=True))
    op.drop_column('users', 'country_timezone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('country_timezone', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('users', 'timezone_name')
    op.drop_column('users', 'country')
    # ### end Alembic commands ###
