"""Add message id column in Giveaway Model

Revision ID: 757c9e70b2f2
Revises: fab7a5b31c24
Create Date: 2025-11-01 01:16:11.248171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '757c9e70b2f2'
down_revision: Union[str, Sequence[str], None] = 'fab7a5b31c24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('giveaways', sa.Column('message_id', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(None, 'giveaways', ['message_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'giveaways', type_='unique')
    op.drop_column('giveaways', 'message_id')
    # ### end Alembic commands ###
