"""Create actual table for Junction Table: tournament_participants

Revision ID: 94872fcb11af
Revises: 6dd1813c357f
Create Date: 2025-10-01 17:28:44.193387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94872fcb11af'
down_revision: Union[str, Sequence[str], None] = '6dd1813c357f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_participants', sa.Column('challonge_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('tournament_participants_tournament_id_fkey'), 'tournament_participants', type_='foreignkey')
    op.drop_constraint(op.f('tournament_participants_user_id_fkey'), 'tournament_participants', type_='foreignkey')
    op.create_foreign_key(None, 'tournament_participants', 'tournaments', ['tournament_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tournament_participants', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournament_participants', type_='foreignkey')
    op.drop_constraint(None, 'tournament_participants', type_='foreignkey')
    op.create_foreign_key(op.f('tournament_participants_user_id_fkey'), 'tournament_participants', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('tournament_participants_tournament_id_fkey'), 'tournament_participants', 'tournaments', ['tournament_id'], ['id'])
    op.drop_column('tournament_participants', 'challonge_id')
    # ### end Alembic commands ###
