"""add scheduled time column in tournament matches

Revision ID: 9bd9dcbf13e1
Revises: 1c9346b310ec
Create Date: 2025-10-07 01:03:27.447848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bd9dcbf13e1'
down_revision: Union[str, Sequence[str], None] = '1c9346b310ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_matches', sa.Column('scheduled_datetime', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament_matches', 'scheduled_datetime')
    # ### end Alembic commands ###
