"""add tournaments.current_tournament

Revision ID: b331a1439300
Revises: 577e9df3ca28
Create Date: 2025-09-30 23:39:31.709001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b331a1439300'
down_revision: Union[str, Sequence[str], None] = '577e9df3ca28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('current_tournament', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'current_tournament')
    # ### end Alembic commands ###
