"""add pvp_experience enum column with default novice

Revision ID: b99403bebda0
Revises: 357d7312af9a
Create Date: 2025-09-19 08:44:57.749514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b99403bebda0'
down_revision: Union[str, Sequence[str], None] = '357d7312af9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pvp_experience', sa.Enum('novice', 'intermediate', 'veteran', name='pvp_experience_enum'), server_default='novice', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pvp_experience')
    # ### end Alembic commands ###
