"""fix battle link column in matches

Revision ID: d8149eb81d65
Revises: 45c17e439e69
Create Date: 2025-10-07 22:08:20.997144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8149eb81d65'
down_revision: Union[str, Sequence[str], None] = '45c17e439e69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_matches', sa.Column('battle_url', sa.Text(), nullable=True))
    op.drop_column('tournament_participants', 'battle_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_participants', sa.Column('battle_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('tournament_matches', 'battle_url')
    # ### end Alembic commands ###
