"""Add Crew wars wins column

Revision ID: ed7b03e4cb2a
Revises: 36a1a16a2b77
Create Date: 2025-10-27 14:33:50.313280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed7b03e4cb2a'
down_revision: Union[str, Sequence[str], None] = '36a1a16a2b77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('crew_wars_wins', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'crew_wars_wins')
    # ### end Alembic commands ###
